name: Tag and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs: 
  extract_info:
    runs-on: windows-latest
    outputs:
      project_name: ${{ steps.get_info.outputs.PACKAGE_NAME }}
      project_version: ${{ steps.get_info.outputs.PACKAGE_VERSION }}
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Get package name and version
      id: get_info
      run: |
        $version = uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version
        $package_name = uvx --from=toml-cli toml get --toml-path=pyproject.toml project.name
        echo "PACKAGE_VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "PACKAGE_NAME=$package_name" >> $env:GITHUB_OUTPUT
    
  tag_and_release:
    needs: extract_info
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Create Git tag
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a v${{ needs.extract_info.outputs.project_version }} -m "v${{ needs.extract_info.outputs.project_version }}"
        if ($LASTEXITCODE) { exit $LASTEXITCODE }
        git push origin v${{ needs.extract_info.outputs.project_version }}
        if ($LASTEXITCODE) { exit $LASTEXITCODE }
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ needs.extract_info.outputs.project_version }}
        name: Release v${{ needs.extract_info.outputs.project_version }}
        generate_release_notes: true
        prerelease: ${{ github.ref != 'refs/heads/main' }}
        